In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./data/non_nans.csv', index_col=0)
df.head()

,Country Name,Indicator Name,1989,1990,1991,1992,1993,1994,1995,1996,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
70287,Algeria,Adjusted net national income (constant 2010 US$),5.151848e+10,5.183382e+10,5.215272e+10,5.158880e+10,4.778696e+10,4.767500e+10,4.779166e+10,4.811183e+10,...,1.223710e+11,1.245078e+11,1.342003e+11,1.353418e+11,1.363548e+11,1.321221e+11,1.417346e+11,1.444864e+11,1.445864e+11,5.899049e+01
70320,Algeria,Age dependency ratio (% of working-age populat...,8.952999e+01,8.764613e+01,8.577588e+01,8.375662e+01,8.157296e+01,7.918647e+01,7.658746e+01,7.406596e+01,...,4.867454e+01,4.921309e+01,4.977822e+01,5.049722e+01,5.150919e+01,5.283779e+01,5.418401e+01,5.580400e+01,5.750803e+01,5.899049e+01
70325,Algeria,Agricultural land (sq. km),3.876000e+05,3.867600e+05,3.862200e+05,3.886500e+05,3.886200e+05,3.964000e+05,3.964900e+05,3.963600e+05,...,4.137400e+05,4.138800e+05,4.139819e+05,4.143164e+05,4.143100e+05,4.145640e+05,4.136020e+05,1.423842e+02,1.484640e+02,1.513617e+02
70493,Algeria,Consumer price index (2010 = 100),1.330392e+01,1.551936e+01,1.953677e+01,2.572399e+01,3.100779e+01,4.001482e+01,5.193109e+01,6.163133e+01,...,1.000000e+02,1.045242e+02,1.138179e+02,1.175218e+02,1.209499e+02,1.267366e+02,1.348449e+02,1.423842e+02,1.484640e+02,1.513617e+02
70664,Algeria,Exports of goods and services (constant 2010 US$),4.403680e+10,4.553405e+10,4.512424e+10,4.688408e+10,4.599329e+10,4.442952e+10,4.722858e+10,5.077072e+10,...,6.195542e+10,6.008788e+10,5.781580e+10,5.452030e+10,5.462934e+10,5.490249e+10,5.874566e+10,5.516218e+10,5.312118e+10,4.988079e+10

In [3]:
df['Indicator Name'].unique()

array(['Adjusted net national income (constant 2010 US$)',
       'Age dependency ratio (% of working-age population)',
       'Agricultural land (sq. km)', 'Consumer price index (2010 = 100)',
       'Exports of goods and services (constant 2010 US$)',
       'Fertility rate, total (births per woman)',
       'GDP (constant 2010 US$)', 'Land area (sq. km)',
       'Life expectancy at birth, total (years)',
       'Mortality rate, under-5 (per 1,000 live births)',
       'Population density (people per sq. km of land area)',
       'Population, total', 'Urban population (% of total population)'],
      dtype=object)

In [4]:
def row_normalization(country, indicator, time_series):
    dict_temp = dict()
    dict_temp['Country Name'] = country
    normalization_values = df[df['Country Name']==country]
    
    if indicator == 'Adjusted net national income (constant 2010 US$)':
        normalization_values = normalization_values[ normalization_values['Indicator Name']=='Population, total'].values[0][2:]
        normalization_values /= 1000
    elif indicator == 'Agricultural land (sq. km)':
        normalization_values = normalization_values[ normalization_values['Indicator Name']=='Land area (sq. km)'].values[0][2:]
    elif indicator == 'Exports of goods and services (constant 2010 US$)':
        normalization_values = normalization_values[ normalization_values['Indicator Name']=='Population, total'].values[0][2:]
        normalization_values /= 1000
    elif indicator == 'Exports of goods and services (constant 2010 US$)':
        normalization_values = normalization_values[ normalization_values['Indicator Name']=='Population, total'].values[0][2:]
        normalization_values /= 1000
    elif indicator == 'GDP (constant 2010 US$)':
        normalization_values = normalization_values[ normalization_values['Indicator Name']=='Population, total'].values[0][2:]
        normalization_values /= 1000
    else:
        normalization_values = 1
    
    time_series = time_series/normalization_values
    dict_temp['Indicator Name'] = indicator
    
    columns = list(df.columns)
    columns = columns[2:]
    
    for year, value in zip(columns, time_series):
        dict_temp[year] = value
    
    return dict_temp

In [5]:
list_normalized = list()
for row in df.iterrows():

    country = row[1][0]
    indicator = row[1][1]
    time_series = row[1][2:].values
    
    list_normalized.append(row_normalization(country, indicator, time_series))
    
    df_normalized = pd.DataFrame(list_normalized)

In [6]:
df_normalized.head()

,Country Name,Indicator Name,1989,1990,1991,1992,1993,1994,1995,1996,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Algeria,Adjusted net national income (constant 2010 US$),2.052023e+06,2.012271e+06,1.975446e+06,1.908694e+06,1.729186e+06,1.689777e+06,1.661869e+06,1.643927e+06,...,3.401323e+06,3.396150e+06,3.589790e+06,3.548539e+06,3.503132e+06,3.325664e+06,3.495184e+06,3.490920e+06,3.423912e+06,1.370181e-03
1,Algeria,Age dependency ratio (% of working-age populat...,8.952999e+01,8.764613e+01,8.577588e+01,8.375662e+01,8.157296e+01,7.918647e+01,7.658746e+01,7.406596e+01,...,4.867454e+01,4.921309e+01,4.977822e+01,5.049722e+01,5.150919e+01,5.283779e+01,5.418401e+01,5.580400e+01,5.750803e+01,5.899049e+01
2,Algeria,Agricultural land (sq. km),1.627382e-01,1.623855e-01,1.621588e-01,1.631790e-01,1.631664e-01,1.664329e-01,1.664707e-01,1.664161e-01,...,1.737133e-01,1.737721e-01,1.738149e-01,1.739553e-01,1.739527e-01,1.740593e-01,1.736554e-01,5.978159e-05,6.233426e-05,6.496209e+00
3,Algeria,Consumer price index (2010 = 100),1.330392e+01,1.551936e+01,1.953677e+01,2.572399e+01,3.100779e+01,4.001482e+01,5.193109e+01,6.163133e+01,...,1.000000e+02,1.045242e+02,1.138179e+02,1.175218e+02,1.209499e+02,1.267366e+02,1.348449e+02,1.423842e+02,1.484640e+02,1.513617e+02
4,Algeria,Exports of goods and services (constant 2010 US$),1.754021e+06,1.767704e+06,1.709221e+06,1.734628e+06,1.664282e+06,1.574746e+06,1.642288e+06,1.734778e+06,...,1.722062e+06,1.638994e+06,1.546543e+06,1.429473e+06,1.403499e+06,1.381959e+06,1.448672e+06,1.332768e+06,1.257948e+06,1.158589e+06

In [7]:
df_normalized.to_csv('./data/normalized_data.csv')